### ISSUE TITLE
Write pwm export() failed for id xx "with open gpiochip0" 

### ISSUE THREAD

**Issue by idalmasso** [hybridgroup/gobot#1077]
Trying to write pwm to a LedDriver with a raspberry pi 4 (fresh install of raspbian) fives the error export() failed for id 26 "with open gpiochip0" (trying to use the pin "37" that is actually GPIO 26). 
This error is actually new in v2.3.0 of gobot (I just reverted to 2.2 and everything works fine).

**Comment by gen2thomas** [comment]
Hi @idalmasso , thanks for finding and report this issue. I will have a look in the next few days.

**Comment by gen2thomas** [comment]
Hi @idalmasso , the PWM usage has changed a bit since 2.3.0.
Until 2.2.0 the pi-blaster was used by default. Now the internal PWMs are used by default and the usage of pi-blaster must be forced by "adaptors.WithPWMUsePiBlaster()". I missed to add this to the migration guide, but it is described in the [README](https://github.com/hybridgroup/gobot/blob/v2.3.0/platforms/raspi/README.md#using-pi-blaster).

If it will not work , please can you provide your program or at least the part for creating the raspi-adaptor and the lines which creates the error output.

Thanks Thomas

**Comment by idalmasso** [comment]
Hello @gen2thomas , thanks for your answer. Yes, I just retried with the WithPWMUsePiBlaster and it seems to be working fine, sorry I had to improve my RTFM capabilities, sorry to have made you lose time!

**Comment by gen2thomas** [comment]
You are welcome, good to hear that it's working now.
