### ISSUE TITLE
Implementation on arduino pulseIn

### ISSUE THREAD

**Issue by chakming** [hybridgroup/gobot#152]
is there any good way to implement pulseIn?
http://arduino.cc/en/Reference/pulseIn

P.S. I'm trying to convert the ultrasonic sensor source code into gobot version:
https://github.com/JRodrigoTech/Ultrasonic-HC-SR04/blob/master/Ultrasonic/Ultrasonic.cpp

**Comment by gen2thomas** [comment]
As already mentioned in various issues, the firmata adaptor is not best suitable to use with this kind of interface (lack of accuracy due to transmission time), but for now it is implemented in gobot for usage with most of all other adaptors, like Raspi, or Tinkerboard. Also the HC-SR04 is available, see #865 .

Therefore I'm going to close this issue as resolved.
