### ISSUE TITLE
Suppor for Teensy boards?

### ISSUE THREAD

**Issue by Symmetric** [hybridgroup/gobot#183]
Currently there's no support listed for the ARM Cortex-M4 based [Teensy 3.1](https://www.pjrc.com/store/teensy31.html) board. Do you have plans to add support for this board?

It's appealing since it has an interrupt-driven USB stack, so it can support high bandwidth applications.

**Comment by zankich** [comment]
@Symmetric I've used gobot on a teensy 3.0 using the [firmata](https://github.com/hybridgroup/gobot/tree/master/platforms/firmata) package, so it should work with the 3.1. The teensy website has more information about firmata compatibility [here](http://www.pjrc.com/teensy/td_libs_Firmata.html). Unfortunately you can't run go directly on the board itself, due to go's runtime requirements.

**Comment by Symmetric** [comment]
Thanks!
