### ISSUE TITLE
Difference between Connection and Adaptor

### ISSUE THREAD

**Issue by saulshanabrook** [hybridgroup/gobot#199]
What is the difference between a `Connection` and an `Adaptor`?

I notice that `Connection` [is just a type alias](https://github.com/hybridgroup/gobot/blob/d18d6cd73aeccf52c69994ed99035e421acf10be/connection.go#L24) for `Adaptor`.

In comment it says:

> A Connection is an instance of an Adaptor

but why create a different type for this?

**Comment by deadprogram** [comment]
Hi @saulshanabrook 

You can use an Adaptor separately if you just want to use Gobot as a library, aka "Metal Gobot".

A Robot has a Connections struct in order to manage each Connection that is under its control. Each Connection is an Adaptor to some type of hardware or software "thing".

Hope that helps! I am going to close this issue, please reopen if needed.
