### ISSUE TITLE
Bebop 2 video streaming via ffmpeg doesn't work

### ISSUE THREAD

**Issue by krancour** [hybridgroup/gobot#608]
Docs and examples show how this can be done, but it doesn't work.

NB: My drone is running the latest firmware.

The problem doesn't seem to lie with ffserver / ffmpeg, as the problem is easily demonstrated even with those removed from the equation.

This bit of code demonstrates:

```
work := func() {
	drone.VideoEnable(true)
	go func() {
		for {
			fmt.Println(<-drone.Video())
		}
	}()
	// ...
}
```

While this should print the raw bytes to `stdout`, it prints nothing.

I'm not sure if the video stream mode (which doesn't seem to be documented anywhere) might be set incorrectly or "stream v2," which enabled RTP on Bebop 2 and Bebop 1 with firmware >= 3.2.0 might have removed ffmpeg support.

**Comment by deadprogram** [comment]
The latest API for Parrot is "documented" in the form of XML files such as https://github.com/Parrot-Developers/arsdk-xml/blob/master/xml/ardrone3.xml

It has been a while since Gobot was updated to match the latest commands. I'd gladly accept a PR that brought the Gobot code into sync with the latest Parrot API.
