### ISSUE TITLE
Keyboard: need up and down event support

### ISSUE THREAD

**Issue by xkenmon** [hybridgroup/gobot#626]
Can the keyboard driver add support for press and release events?

like [this](https://github.com/go-vgo/robotgo/blob/master/examples/event/main.go), but more beautiful

**Comment by trevrosen** [comment]
This isn't possible with the current driver implementation. There's been some discussion around implementing a generic communications channel that implicates a browser for this kind of thing because then you can leverage DOM events to get these events w/out having to deal w/ cross-platform issues, but there's no plan to alter the current driver to use anything other than `stty`

So because a resolution isn't possible without significant other work, I'm going to close this issue for now. This is the 2nd or 3rd time that this feature has been requested though, so that will factor into roadmap.

Thanks for your interest in Gobot!
