### ISSUE TITLE
Error installing while using Go Modules due to outdated dependency name

### ISSUE THREAD

**Issue by jshields** [hybridgroup/gobot#689]
When installing using the instructions from https://gobot.io/ using Go 1.13 and Go Modules, an error occurs like so
```
~/workspace/dronez(master): go get -u gobot.io/x/gobot/...
...
go: github.com/codegangsta/cli@v1.22.1: parsing go.mod: unexpected module path "github.com/urfave/cli"
go: error loading module requirements
```

This is due to the usage of the dependency "github.com/codegangsta/cli", which has been renamed to "github.com/urfave/cli"

(See that https://github.com/codegangsta/cli redirects to https://github.com/urfave/cli)

https://github.com/hybridgroup/gobot/blob/635adea96f788ab19bf77470b075f8db44d34fa0/cli/main.go#L6

**Comment by deadprogram** [comment]
Got it. Would you like to submit a PR that corrects this?

**Comment by jshields** [comment]
@deadprogram Sure thing :) Gotta install dep to update the lock file, then I'll send that over.

**Comment by jshields** [comment]
I opened https://github.com/hybridgroup/gobot/pull/690
Feel free to suggest another version of `dep` I should use or different settings for generating the lock file.

**Comment by MShoaei** [comment]
This issue is kind of forgotten but maybe it's a good time to consider migrating to go modules. Also there are **2 dependencies** that need to be fixed and the second one is in platform/nats. I have them fixed and also tried migrating to go modules and I'm  ready to make the PR.
Just making sure if you want to consider migrating to go modules. Here's my [repo](https://github.com/MShoaei/gobot) if you want to check it out.

**Comment by jshields** [comment]
@MShoaei Agreed, moving to Go Modules is the long term solution.

**Comment by deadprogram** [comment]
I have just merged the `dep` PR, and would gladly accept a PR to move to modules!

**Comment by deadprogram** [comment]
The modules code is now in the `dev`` branch.

**Comment by deadprogram** [comment]
This has now been released. Thanks everyone!
