### ISSUE TITLE
[question, ble] go ble-serial

### ISSUE THREAD

**Issue by vlappa** [hybridgroup/gobot#987]
Hi,
I want to make something like this, but then in Go:
https://github.com/Jakeler/ble-serial/blob/a429060faf6dfe38615af28712afa8ee4ef271fd/examples/ble_standalone.py#L5

Is it possible with this library? Any examples available for using the SerialPort?

What are address, rid and tid here?
https://github.com/hybridgroup/gobot/blob/v2.1.1/platforms/ble/serial_port.go#L19

Or is there a better way to get data from bluetooth (using Linux)?

**Comment by gen2thomas** [comment]
Hi @vlappa , because the feature is inspired by https://github.com/monteslu/ble-serial, I assume the rid and tid are  optional values for "transmitCharacteristic" and "receiveCharacteristic". See also the [comment for Subscribe](https://github.com/hybridgroup/gobot/blob/ba8136ff1ccb8aa93f31ef74b7b0df0f22d7ef8a/platforms/ble/ble_client_adaptor.go#L196C40-L196C40) - usage of "rid" and [the name of the write methode](https://github.com/hybridgroup/gobot/blob/ba8136ff1ccb8aa93f31ef74b7b0df0f22d7ef8a/platforms/ble/serial_port.go#L64) - usage of tid.

Hope this helps

**Comment by gen2thomas** [comment]
Please refer now to examples with usage of bleclient and serialport.

**Comment by gen2thomas** [comment]
Fixed with [v2.4.0](https://github.com/hybridgroup/gobot/releases/tag/v2.4.0)
